//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Layout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int hid { get; set; }
        public string hn { get; set; }
        public Nullable<int> py { get; set; }
    }
}
